server:
  port: 1112
  servlet:
    contextPath: /api

spring:
  application:
    name: BookStoreApi

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_db
    username: user
    password: password

  bookService:
    host: https://scb-test-book-publisher.herokuapp.com
    endpoint:
      getInfo: books


restTemplate:
  connectionTimeOut: 5000
  readTimeOut: 10000
