server:
  port: 1112
  servlet:
    contextPath: /api

spring:
  application:
    name: BookStoreApi

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password

  bookService:
    host: https://scb-test-book-publisher.herokuapp.com
    endpoint:
      getInfo: books
      getInfoRecommend: books/recommendation

  oauth:
    url: http://localhost:1112/api/oauth/token?grant_type=password&username=


restTemplate:
  connectionTimeOut: 5000
  readTimeOut: 10000
